### ISSUE TITLE
Match operator

### ISSUE THREAD

**Issue by rishiosaur** [rishiosaur/sepia#20]
Proposed example syntax:
```
value z = x :: {
	"hello" => true,
	"world" => false,
	_ => false
}
```

This would also change the `fib` example to something like:

```
value fibonacci = |n| -> n :: {
	0 => 0,
	1 => 1,
	2 => 1,
	_ => fibonacci(n - 1) + fibonacci(n - 2)
} end

print(fibonacci(5))
```

The match operator is an infix expression.

**Comment by rishiosaur** [comment]
@quackduck said that using `->` instead of `=>` to keep syntax consistent.

**Comment by rishiosaur** [comment]
*Updated example:*

Proposed example syntax:
```
value z = x :: {
	"hello" -> true,
	"world" -> false,
	_ -> false
}
```
This would also change the fib example to something like:
```
value fibonacci = |n| -> n :: {
	0 -> 0,
	1 -> 1,
	2 -> 1,
	_ -> fibonacci(n - 1) + fibonacci(n - 2)
} end

print(fibonacci(5))
```
The match operator is an infix expression.

**Comment by rishiosaur** [comment]
Argh it looks like we're going to have to build in a new keyword for prefix parsing—Sepia's current architecture doesn't allow for this weird stuff

**Comment by quackduck** [comment]
The `end` seems a bit redundant to me- the curly brackets already indicate an end.

**Comment by sarthaktexas** [comment]
wait wouldnt `=>` be better tho?

**Comment by quackduck** [comment]
Wait wait I just said to use one of them to be consistent. I think both look alright. `=>` has an equals sign in it so it might be better for showing mapping. 

Could you explain `value fibonacci = |n| -> n :: {` to me? Why that syntax?

**Comment by safinsingh** [comment]
@quackduck i'd imagine it's a closure with the parameter `n` that matches `n` and that block/machine returns a value which is what is assigned to `fibonacci`

**Comment by quackduck** [comment]
Ah okay. I've never done closures so I didn't understand that.
